### PR TITLE
This should work

### PR DESCRIPTION
**Pull request by muschellij2**
Had to encode the timezone for `acc_running$date_time` to `UTC` and resave to get this to work.  You can check it out at https://travis-ci.com/muschellij2/adept/builds. A lot are running so you can also double check on your PR: https://travis-ci.com/martakarass/adept/pull_requests

### CODE REVIEW

**Comment by martakarass** [comment]
I see one version failed on the tests. I suggest I pull your changes and
work on this now.

So many thanks for that help!!!

Bests / Pozdrawiam,
Marta Karas

**Comment by muschellij2** [comment]
It looks like it's working on Mac, but failing on Linux: https://travis-ci.org/martakarass/adept/builds/501278775

**Comment by martakarass** [comment]
I debugged that the error comes from test failing, that is, a one-index
difference in identifying the beginning of a stride. In this example, the
index of the beginning is being identified solely via fining maximum of the
similarity matrix:

similarity.mat.MAX <- max(similarity.mat, na.rm = TRUE)
# (...)
similarity.mat.MAX.IDX <- which(similarity.mat == similarity.mat.MAX,
arr.ind = TRUE)[1, ]

In the example that fails the test on linux we have:

> options(digits = 22)
> similarity.mat.i[, c(364:367)]
                          [,1]                      [,2]
  [,3]                      [,4]
[1,]  0.6296889347353464838619  0.6348018277753479932102
0.6348018277753481042325  0.6296889347353461507950
[2,] -0.3126258415947771873711 -0.3498580773656219111700
-0.3857038146625820229652 -0.4199403064978239896732

I presume max identifies maximum from this part as [1,3] of above matrix
subset (yah! it is larger starting from 15th place after the comma),
whereas linux as  [1,2].

**Comment by martakarass** [comment]
Very unfortunate and hardly reproducible IMHO. Do you have a suggestion on
how to deal with it? Slightly modify the test?

Bests / Pozdrawiam,
Marta Karas

**Comment by muschellij2** [comment]
I would maybe bring this up to r-devel.

So those values are (in essence) exactly the same?  You can use a tolerance
measure or which.max which will return the first one.  See
https://stackoverflow.com/questions/17404513/floating-point-equality-and-tolerances

John

**Comment by muschellij2** [comment]
https://www.burns-stat.com/documents/tutorials/impatient-r/more-r-key-objects/more-r-numbers/
John

**Comment by martakarass** [comment]
*#1 *
I did not use which.max on purpose as I want to check if the max value
passes a certain threshold - it happens in the line of "# (...)"

similarity.mat.MAX <- max(similarity.mat, na.rm = TRUE)
# (...)
similarity.mat.MAX.IDX <- which(similarity.mat == similarity.mat.MAX,
arr.ind = TRUE)[1, ]

*#2*
Setting tolerance in the equality check sounds good, but I have just
checked and it is 10 TIMES SLOWER, unfortunately! This operation is
executed multiple times within one run of the algorithm, hence I am
hesitating from using this solution.  I think I will keep it as it is now,
without a change, accepting the fact the difference may happen in some
ultra extreme rare cases (unlikely in not simulated scenarios).

set.seed(1)
mat1 <- matrix(runif(6000 * 100), ncol = 6000)
tol <- 1e-10
mat1.max <- max(mat1, na.rm = TRUE)
library(rbenchmark)
out <- benchmark("approach_NEW" =
                   {mat1.max.idx <- which((mat1 - mat1.max) < tol, arr.ind
= TRUE)[1, ]
                   },
                 "approach_OLD" = {
                   mat1.max.idx <- which(mat1 ==  mat1.max, arr.ind =
TRUE)[1, ]
                   },
                 replications = 1000,
                 columns = c("test", "replications", "elapsed",
                             "relative", "user.self", "sys.self"))
out
#           test replications elapsed relative user.self sys.self
# 1 approach_NEW         1000  20.822     9.73    20.163    0.630
# 2 approach_OLD         1000   2.140     1.00     1.947    0.191

**Comment by martakarass** [comment]
I have corrected one line in "APPROACH_OLD" and it takes 1.6 times the old
solution.

set.seed(1)
mat1 <- matrix(runif(6000 * 100), ncol = 6000)
tol <- 1e-10
mat1.max <- max(mat1, na.rm = TRUE)
library(rbenchmark)
out <- benchmark("approach_NEW" =
                   {mat1.max.idx <- which((mat1 + tol) >= mat1.max, arr.ind
= TRUE)[1, ]
                   },
                 "approach_OLD" = {
                   mat1.max.idx <- which(mat1 ==  mat1.max, arr.ind =
TRUE)[1, ]
                   },
                 replications = 1000,
                 columns = c("test", "replications", "elapsed",
                             "relative", "user.self", "sys.self"))
out
#           test replications elapsed relative user.self sys.self
# 1 approach_NEW         1000   3.007    1.661     2.685    0.314
# 2 approach_OLD         1000   1.810    1.000     1.644    0.167

Bests / Pozdrawiam,
Marta Karas

**Pull request merged**
